spring.application.name=mobile-app-ws
spring.datasource.username=sergey
spring.datasource.password=sergey
spring.datasource.url=jdbc:mysql://localhost:3306/photo_app
spring.jpa.hibernate.ddl-auto=update

server.error.include-message=always
server.error.include-binding-errors=always

tokenSecret=k9m2xv7bq0n5r8t1s6d3f4g7h2j9k8l0p5w1e6r3t9y2u7i4o8a5s1d6f3g0h9j2
server.servlet.context-path=/mobile-app-ws


logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.appsdeveloperblog=DEBUG